### ISSUE TITLE
BigFan: NetHunter নেতাহান্তার ষ্যাড়

### ISSUE THREAD

**Issue by PiprTuff** [darknethaxor/haxor#1]

**Comment by darknethaxor** [comment]
Same to You

**Comment by Ozovehealiu15** [comment]
Nice one

**Comment by Marhein963** [comment]
Sup dude, I'm having a super annoying issue with termux when I try to run NetHunter and I was hoping U could help me. The problem seems unsolvable, some how my I can run a VNC connection for any linger than 5 min, it's getting very annoying. 

When I run NetHunter on Termux and run the command kex I always get a VNC connection but after some minutes the server always falls down. Can U help me with that?

Ps: I'm currently running NetHunter Rootless.

![Screenshot_20220506-182906_Termux.jpg](https://user-images.githubusercontent.com/105091284/167234488-a4733d34-dae3-449f-b080-c99c9d8cdae1.jpg)

After several minutes this message always appears: [Process completed (signal 9) - press Enter]. 

I can run Termux on background for hours but as soon as I star running a VNC connection by Kex on NetHunter it's just some minutes before Termux kill all process.
